### ISSUE TITLE
SDK for python

### ISSUE THREAD

**Issue by AndyCC25** [DoubangoTelecom/ultimateCreditCard-SDK#19]
Hi, I didn't find some docs to build the binaries using python

**Comment by DoubangoTelecom** [comment]
For now we haven't published the python docs

**Comment by DoubangoTelecom** [comment]
Just to make it clear, this issue is closed by 2.3.0 because we added support for Python. The sample is at https://github.com/DoubangoTelecom/ultimateCreditCard-SDK/tree/master/samples/python/recognizer
