### ISSUE TITLE
Different result in C++ recognizer and webApp

### ISSUE THREAD

**Issue by Polarbeargo** [DoubangoTelecom/ultimateCreditCard-SDK#21]
Hello @DoubangoTelecom,

I use docker to run C++ recognizer but the result is different compare to the webApp. It seems to have difficulty recognize 6 and 8 is that normal? Is there any method to improve accuracy to recognize digit 6 and 8?
![docker cli docker](https://user-images.githubusercontent.com/8589224/93854791-f1f1f680-fce8-11ea-8ba0-5c079c2841ed.png)
![Document](https://user-images.githubusercontent.com/8589224/93854814-fe764f00-fce8-11ea-8a05-be42ad7c8207.png)
![vityim](https://user-images.githubusercontent.com/8589224/93855065-6f1d6b80-fce9-11ea-9b3b-87be9a92e57d.png)
![city](https://user-images.githubusercontent.com/8589224/93855079-75abe300-fce9-11ea-892c-0f6cb665188d.png)

**Comment by DoubangoTelecom** [comment]
This is a trial version and these numbers are hidden on purpose

**Comment by Polarbeargo** [comment]
Thank you @DoubangoTelecom :D
