### ISSUE TITLE
Sample app failing in android studio

### ISSUE THREAD

**Issue by chetanunadkat90** [DoubangoTelecom/ultimateCreditCard-SDK#37]
Sample app is failing to run with following error : 
A/org.doubango.compv: ****[COMPV FATAL]: function: "newPtr()" 
    file: "..\source\ultimate_ocr_tensorflowlite_interpreter.cxx" 
    line: "514" 
    message: Assertion failed!
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5490 (imateCreditCard), pid 5490 (imateCreditCard)

**Comment by DoubangoTelecom** [comment]
Please attach full logs.

**Comment by chetanunadkat90** [comment]
10/02 22:06:52: Launching 'ccardvideorecognizer' on OnePlus GM1901.
Install successfully finished in 1 s 318 ms.
$ adb shell am start -n "org.doubango.ultimateCreditCard/org.doubango.ultimateCreditCard.CCardVideoRecognizerActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 5490 on device 'oneplus-gm1901-00160cec'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/imateCreditCar: Accessing hidden field Landroid/content/res/ResourcesKey;->mOverrideConfiguration:Landroid/content/res/Configuration; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/content/res/ResourcesKey;->mCompatInfo:Landroid/content/res/CompatibilityInfo; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/content/res/ResourcesKey;->mLoaders:[Landroid/content/res/loader/ResourcesLoader; (blacklist, linking, denied)
    Accessing hidden method Landroid/content/res/ResourcesKey;-><init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;[Landroid/content/res/loader/ResourcesLoader;)V (blacklist, linking, denied)
    Accessing hidden field Landroid/content/res/ResourcesKey;->mLibDirs:[Ljava/lang/String; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/content/res/ResourcesKey;->mLibDirs:[Ljava/lang/String; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/content/res/ResourcesKey;->mOverlayDirs:[Ljava/lang/String; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/content/res/ResourcesKey;->mDisplayId:I (greylist-max-o, linking, denied)
W/imateCreditCar: Accessing hidden field Landroid/content/res/ResourcesKey;->mOverrideConfiguration:Landroid/content/res/Configuration; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/content/res/ResourcesKey;->mCompatInfo:Landroid/content/res/CompatibilityInfo; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/content/res/ResourcesKey;->mLoaders:[Landroid/content/res/loader/ResourcesLoader; (blacklist, linking, denied)
    Accessing hidden method Landroid/content/res/ResourcesKey;-><init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;[Landroid/content/res/loader/ResourcesLoader;)V (blacklist, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->redirectResourcesToNewImplLocked(Landroid/util/ArrayMap;)V (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->applyCompatConfigurationLocked(ILandroid/content/res/Configuration;)Z (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager;->mResCompatibilityInfo:Landroid/content/res/CompatibilityInfo; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/content/res/CompatibilityInfo;->supportsScreen()Z (greylist, linking, allowed)
    Accessing hidden field Landroid/app/ResourcesManager;->mResCompatibilityInfo:Landroid/content/res/CompatibilityInfo; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/content/res/CompatibilityInfo;->applyToConfiguration(ILandroid/content/res/Configuration;)V (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->applyConfigurationToResources(Landroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;)Z (blacklist, linking, denied)
W/imateCreditCar: Accessing hidden method Landroid/app/ResourcesManager;->applyConfigurationToResourcesLocked(Landroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;Landroid/view/DisplayAdjustments;)Z (blacklist, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->applyConfigurationToResourcesLocked(Landroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;)Z (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->applyConfigurationToResourcesLocked(Landroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;Landroid/view/DisplayAdjustments;)Z (blacklist, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->applyConfigurationToResourcesLocked(Landroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;Landroid/view/DisplayAdjustments;)Z (blacklist, linking, denied)
    Accessing hidden method Landroid/content/res/Configuration;->isOtherSeqNewer(Landroid/content/res/Configuration;)Z (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->applyNewResourceDirsLocked(Landroid/content/pm/ApplicationInfo;[Ljava/lang/String;)V (blacklist, linking, denied)
    Accessing hidden method Landroid/content/pm/ApplicationInfo;->getBaseCodePath()Ljava/lang/String; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->createAssetManager(Landroid/content/res/ResourcesKey;)Landroid/content/res/AssetManager; (greylist, linking, allowed)
    Accessing hidden method Landroid/app/ResourcesManager;->createAssetManager(Landroid/content/res/ResourcesKey;Landroid/app/ResourcesManager$ApkAssetsSupplier;)Landroid/content/res/AssetManager; (blacklist, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->createBaseTokenResources(Landroid/os/IBinder;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;Ljava/lang/ClassLoader;Ljava/util/List;)Landroid/content/res/Resources; (blacklist, linking, denied)
W/imateCreditCar: Accessing hidden method Landroid/content/res/ResourcesKey;-><init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;[Landroid/content/res/loader/ResourcesLoader;)V (blacklist, linking, denied)
I/chatty: uid=10112(org.doubango.ultimateCreditCard) re-initialized> identical 1 line
W/imateCreditCar: Accessing hidden method Landroid/content/res/ResourcesKey;-><init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;[Landroid/content/res/loader/ResourcesLoader;)V (blacklist, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->dump(Ljava/lang/String;Ljava/io/PrintWriter;)V (greylist-max-o, linking, denied)
    Accessing hidden method Lcom/android/internal/util/IndentingPrintWriter;-><init>(Ljava/io/Writer;Ljava/lang/String;)V (greylist, linking, allowed)
    Accessing hidden method Lcom/android/internal/util/IndentingPrintWriter;->increaseIndent()Lcom/android/internal/util/IndentingPrintWriter; (greylist, linking, allowed)
    Accessing hidden field Landroid/app/ResourcesManager;->mCachedApkAssets:Landroid/util/ArrayMap; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->countLiveReferences(Ljava/util/Collection;)I (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->getAdjustedDisplay(ILandroid/content/res/Resources;)Landroid/view/Display; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/hardware/display/DisplayManagerGlobal;->getCompatibleDisplay(ILandroid/content/res/Resources;)Landroid/view/Display; (greylist-max-o, linking, denied)
W/imateCreditCar: Accessing hidden method Landroid/app/ResourcesManager;->getConfiguration()Landroid/content/res/Configuration; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->getDisplayMetrics()Landroid/util/DisplayMetrics; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/view/DisplayAdjustments;->DEFAULT_DISPLAY_ADJUSTMENTS:Landroid/view/DisplayAdjustments; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->getDisplayMetrics(ILandroid/view/DisplayAdjustments;)Landroid/util/DisplayMetrics; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->getDisplayMetrics(ILandroid/view/DisplayAdjustments;)Landroid/util/DisplayMetrics; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->getAdjustedDisplay(ILandroid/view/DisplayAdjustments;)Landroid/view/Display; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->getResources(Landroid/os/IBinder;Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;Ljava/lang/ClassLoader;Ljava/util/List;)Landroid/content/res/Resources; (blacklist, linking, denied)
    Accessing hidden method Landroid/content/res/ResourcesKey;-><init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;[Landroid/content/res/loader/ResourcesLoader;)V (blacklist, linking, denied)
I/chatty: uid=10112(org.doubango.ultimateCreditCard) re-initialized> identical 1 line
W/imateCreditCar: Accessing hidden method Landroid/content/res/ResourcesKey;-><init>(Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;ILandroid/content/res/Configuration;Landroid/content/res/CompatibilityInfo;[Landroid/content/res/loader/ResourcesLoader;)V (blacklist, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->invalidatePath(Ljava/lang/String;)V (greylist-max-o, linking, denied)
W/imateCreditCar: Accessing hidden method Landroid/content/res/ResourcesKey;->isPathReferenced(Ljava/lang/String;)Z (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager;->mCachedApkAssets:Landroid/util/ArrayMap; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager;->mCachedApkAssets:Landroid/util/ArrayMap; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager$ApkKey;->path:Ljava/lang/String; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager;->mCachedApkAssets:Landroid/util/ArrayMap; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/content/res/ApkAssets;->close()V (blacklist, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager;->mCachedApkAssets:Landroid/util/ArrayMap; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager$ApkKey;->path:Ljava/lang/String; (greylist-max-o, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager;->mCachedApkAssets:Landroid/util/ArrayMap; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/content/res/ApkAssets;->close()V (blacklist, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->isSameResourcesOverrideConfig(Landroid/os/IBinder;Landroid/content/res/Configuration;)Z (greylist-max-o, linking, denied)
W/imateCreditCar: Accessing hidden field Landroid/app/ResourcesManager$ActivityResources;->overrideConfig:Landroid/content/res/Configuration; (greylist-max-o, linking, denied)
I/chatty: uid=10112(org.doubango.ultimateCreditCard) re-initialized> identical 1 line
W/imateCreditCar: Accessing hidden field Landroid/app/ResourcesManager$ActivityResources;->overrideConfig:Landroid/content/res/Configuration; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/content/res/Configuration;->diffPublicOnly(Landroid/content/res/Configuration;)I (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->overrideTokenDisplayAdjustments(Landroid/os/IBinder;Ljava/util/function/Consumer;)Z (blacklist, linking, denied)
    Accessing hidden field Landroid/app/ResourcesManager$ActivityResources;->activityResources:Ljava/util/ArrayList; (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/content/res/Resources;->overrideDisplayAdjustments(Ljava/util/function/Consumer;)V (blacklist, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->updateResourcesForActivity(Landroid/os/IBinder;Landroid/content/res/Configuration;IZ)V (greylist-max-o, linking, denied)
    Accessing hidden method Landroid/app/ResourcesManager;->getOrCreateActivityResourcesStructLocked(Landroid/os/IBinder;)Landroid/app/ResourcesManager$ActivityResources; (greylist-max-o, linking, denied)
W/imateCreditCar: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
    Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
I/studio.deploy: Finished instrumenting
D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
I/100: Open /data/app/~~iml1pnCCJF0RhuEUlcI69w==/org.doubango.ultimateCreditCard-OaI73w5vLz0fLGZQAkNV_Q==/base.apk took:75ms
I/imateCreditCar: failed to find target package for overlay /system/product/overlay/ProductOverlay-oneplus-framework-res.apk
I/imateCreditCar: failed to find target package for overlay /system/system_ext/overlay/CommonOverlay-oneplus-framework-res.apk
    failed to find target package for overlay /odm/overlay/OdmOverlay-oneplus-framework-res.apk
I/Perf: Connecting to perf service.
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
E/Config:Grabber:OnePlusFontConfig: Index 0 requested, with a size of 0
I/imateCreditCar: failed to find target package for overlay /system/product/overlay/ProductOverlay-oneplus-framework-res.apk
    failed to find target package for overlay /system/system_ext/overlay/CommonOverlay-oneplus-framework-res.apk
    failed to find target package for overlay /odm/overlay/OdmOverlay-oneplus-framework-res.apk
E/imateCreditCar: [frame_perf] perfboost open tb_ctl file failed, isApp[1], errno=No such file or directory
E/libprocessgroup: set_timerslack_ns write failed: Operation not permitted
I/imateCreditCar: failed to find target package for overlay /system/product/overlay/ProductOverlay-oneplus-framework-res.apk
    failed to find target package for overlay /system/system_ext/overlay/CommonOverlay-oneplus-framework-res.apk
    failed to find target package for overlay /odm/overlay/OdmOverlay-oneplus-framework-res.apk
I/org.doubango.ultimateCreditCard.CCardVideoRecognizerActivity: onCreate org.doubango.ultimateCreditCard.CCardVideoRecognizerActivity@b66f4fe
I/org.doubango.ultimateCreditCard.common.CCardActivity: onCreate org.doubango.ultimateCreditCard.CCardVideoRecognizerActivity@b66f4fe
W/imateCreditCar: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/imateCreditCar: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
W/linker: Warning: "/data/app/~~iml1pnCCJF0RhuEUlcI69w==/org.doubango.ultimateCreditCard-OaI73w5vLz0fLGZQAkNV_Q==/lib/arm64/libtensorflowlite.so" unused DT entry: DT_RPATH (type 0xf arg 0x27171) (ignoring)
I/org.doubango.compv: *[COMPV INFO]: [UltCreditCardSdkEngine] *************** JNI_OnLoad ****************
I/org.doubango.compv: *[COMPV INFO]: [UltCreditCardSdkEngine] Call: init
    *[COMPV INFO]: [UltCreditCardSdkEngine] jsonConfig: {"debug_level":"info","debug_write_input_image_enabled":false,"debug_internal_data_path":"\/storage\/emulated\/0\/Android\/data\/org.doubango.ultimateCreditCard\/files","num_threads":-1,"gpgpu_enabled":true,"ielcd_enabled":false,"detect_minscore":0.5,"detect_roi":[0,0,0,0],"recogn_minscore":0.2,"recogn_score_type":"min","recogn_rectify_enabled":false}
    *[COMPV INFO]: [UltCreditCardSdkEngine] **** Copyright (C) 2011-2021 Doubango Telecom <https://www.doubango.org> ****
    ultimateCreditCard-SDK <https://github.com/DoubangoTelecom/ultimateCreditCard-SDK> version 2.4.0
I/org.doubango.compv: *[COMPV INFO]: [UltCreditCardSdkEngine] AAssetManager successfully defined. The engine owe the AAssetManager and must clear it at deInit.
    *[COMPV INFO]: [CompVBase] Initializing [base] modules (v 1.0.0, nt -1)...
    *[COMPV INFO]: [CompVBase] sizeof(compv_scalar_t)= #8
    *[COMPV INFO]: [CompVBase] sizeof(float)= #4
    *[COMPV INFO]: [CompVBase] [Base] module: android static API version: 21
    *[COMPV INFO]: Initializing window registery
I/org.doubango.compv: *[COMPV INFO]: [ImageDecoder] Initializing image decoder...
I/org.doubango.compv: *[COMPV INFO]: /!\ Code in file '..\compv_cpu.cxx' in function 'init' starting at line #635: _SC_LEVEL1_DCACHE_LINESIZE and _SC_LEVEL1_DCACHE_SIZE not availabe and Android
    *[COMPV INFO]: [CompVCpu] H: 'Qualcomm Technologies, Inc SM8150', S: '', M: '', MN: ''
    *[COMPV INFO]: [CompVBase] CPU features: [arm];[arm64];neon;neon_fma;vfpv3;vfpv4;
    *[COMPV INFO]: [CompVBase] CPU cores: #8
    *[COMPV INFO]: [CompVBase] CPU cache1: line size: #64B, size :#4KB
    *[COMPV INFO]: [CompVBase] CPU Phys RAM size: #5474GB
    *[COMPV INFO]: [CompVBase] CPU endianness: LITTLE
    *[COMPV INFO]: [CompVBase] Binary type: AArch64
    *[COMPV INFO]: [CompVBase] Intrinsic enabled
    *[COMPV INFO]: [CompVBase] Assembler enabled
    *[COMPV INFO]: [CompVBase] Code built with debug enabled
    *[COMPV INFO]: [CompVBase] OS name: Android
    *[COMPV INFO]: [CompVBase] Math Fast Trig.: true
    *[COMPV INFO]: [CompVBase] Math Fixed Point: true
    *[COMPV INFO]: [CompVMathExp] Init
    *[COMPV INFO]: [CompVBase] Default alignment: #32
    *[COMPV INFO]: [CompVBase] Best alignment: #32
    *[COMPV INFO]: [CompVMem] Memory check enabled for debugging, this may slowdown the code
    *[COMPV INFO]: [CompVBase] Heap limit: #280304KB (#273MB)
    *[COMPV INFO]: [CompVParallel] Initializing [parallel] module...
I/org.doubango.compv: *[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=1,set=useless, threadId:0x75b538ccc0, kThreadSetAffinity:false) - ENTER
I/org.doubango.compv: *[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=2,set=useless, threadId:0x75b528ecc0, kThreadSetAffinity:false) - ENTER
I/org.doubango.compv: *[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=5,set=useless, threadId:0x75b4f94cc0, kThreadSetAffinity:false) - ENTER
I/org.doubango.compv: *[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=4,set=useless, threadId:0x75b5092cc0, kThreadSetAffinity:false) - ENTER
I/org.doubango.compv: *[COMPV INFO]: [CompVThreadDispatcher] Thread dispatcher created with #8 threads/#8 cores
    *[COMPV INFO]: [CompVParallel] [Parallel] module initialized
    *[COMPV INFO]: [CompVBase] [Base] modules initialized
I/org.doubango.compv: *[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=3,set=useless, threadId:0x75b5190cc0, kThreadSetAffinity:false) - ENTER
I/org.doubango.compv: *[COMPV INFO]: [CompVCore] Initializing [core] module (v 1.0.0)...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 1 and name = 'FAST (Features from Accelerated Segment Test)'...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 8 and name = 'ORB (Oriented FAST and Rotated BRIEF)'...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 27 and name = 'Sobel edge detector'...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 28 and name = 'Scharr edge detector'...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 29 and name = 'Prewitt edge detector'...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 20 and name = 'Canny edge detector'...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 30 and name = 'Hough standard (STD)'...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 31 and name = 'Kernel-based Hough transform (KHT)'...
    *[COMPV INFO]: [CompVFeature] Registering feature factory with id = 41 and name = 'Standard Histogram of oriented gradients (S-HOG)'...
    *[COMPV INFO]: [CompVMatcher] Registering matcher factory with id = 0 and name = 'Brute force matcher'...
    *[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 1 and name = 'PLSL (Parallel Light Speed Labeling)'...
    *[COMPV INFO]: [CompVConnectedComponentLabeling] Registering connected component labeling factory with id = 19 and name = 'LMSER (Linear Time Maximally Stable Extremal Regions)'...
I/org.doubango.compv: *[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=0,set=useless, threadId:0x75b548acc0, kThreadSetAffinity:false) - ENTER
I/org.doubango.compv: *[COMPV INFO]: [CompVGL] Initializing [gl] module (v 1.0.0)...
    *[COMPV INFO]: [CompVGL] android API version: 21
    *[COMPV INFO]: [CompVGL] OpenGL-ES implementation enabled
    *[COMPV INFO]: [CompVGL] OpenGL-ES 2.0 API
I/org.doubango.compv: *[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=7,set=useless, threadId:0x75b1d98cc0, kThreadSetAffinity:false) - ENTER
I/org.doubango.compv: *[COMPV INFO]: [CompVAsyncTask11] run(coreId:requested=6,set=useless, threadId:0x75b4e96cc0, kThreadSetAffinity:false) - ENTER
I/org.doubango.compv: *[COMPV INFO]: [CompVSharedLib] Loaded shared lib: libGLESv2.so
    *[COMPV INFO]: [CompVGLVAO] 'libGLESv2.so' file loaded: bindVertexArrayOES=YES, deleteVertexArraysOES=YES, genVertexArraysOES=YES, isVertexArrayOES=YES
    *[COMPV INFO]: [CompVGL] GL module initialized
    *[COMPV INFO]: [CompVGpu] Initializing [gpu] module (v 1.0.0)...
    *[COMPV INFO]: [CompVCamera] Initializing [camera] module (v 1.0.0)...
    *[COMPV INFO]: [CompVDrawing] Initializing [drawing] module (v 1.0.0)...
    *[COMPV INFO]: [CompVDrawing] [Drawing] module: android API version: 21
    *[COMPV INFO]: Setting window factory: AndroidEGL
    *[COMPV INFO]: [CompVDrawing] /!\ No jpeg decoder found
    *[COMPV INFO]: [CompVDrawing] Drawing module initialized
    *[COMPV INFO]: [CompVGpu] GPU enabled: true
    *[COMPV INFO]: /!\ Code in file '..\source\ultimate_base_engine.cxx' in function 'init' starting at line #75: Not optimized for GPU -> GPGPU computing not enabled or deactivated
    *[COMPV INFO]: [UltBaseOpenCL] Trying to load [libOpenCL.so]
I/org.doubango.compv: *[COMPV INFO]: [UltBaseOpenCL] Loaded [libOpenCL.so], looksLikeValid: yes...
I/org.doubango.compv: *[COMPV INFO]: [UltBaseOpenCLUtils] Selected platform vendor: QUALCOMM
I/org.doubango.compv: *[COMPV INFO]: [UltBaseOpenCLUtils] deviceCount=1
    *[COMPV INFO]: [UltBaseOpenCLUtils] Device -> name: QUALCOMM Adreno(TM), id: 0x75acba01e0
I/org.doubango.compv: *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT=1
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE=0
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_COMPUTE_UNITS=2
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS=3
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_ITEM_SIZES=1024, 1024, 1024, 
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_WORK_GROUP_SIZE=1024
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_CLOCK_FREQUENCY=1 MHz
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE=64 B
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_GLOBAL_MEM_SIZE=2870317056 B (2737 MB)
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_LOCAL_MEM_SIZE=32768 B (32 KB)
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_MAX_MEM_ALLOC_SIZE=684 MB
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_PLATFORM_VERSION=OpenCL 2.0 QUALCOMM build: commit #559e78c changeid #Ib9d997268a Date: 10/13/20 Tue Local Branch: mybrancheb0d76cb-f27a-f1ff-9cdc-1458d0b52ae8 Remote Branch: quic/gfx-adreno.lnx.1.0.r99-rel
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_VERSION=OpenCL 2.0 Adreno(TM) 640
I/org.doubango.compv: *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DRIVER_VERSION=OpenCL 2.0 QUALCOMM build: commit #559e78c changeid #Ib9d997268a Date: 10/13/20 Tue Local Branch: mybrancheb0d76cb-f27a-f1ff-9cdc-1458d0b52ae8 Remote Branch: quic/gfx-adreno.lnx.1.0.r99-rel Compiler E031.37.12.01
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_OPENCL_C_VERSION=OpenCL C 2.0 Adreno(TM) 640
    *[COMPV INFO]: [UltBaseOpenCLUtils] CL_DEVICE_EXTENSIONS=cl_khr_3d_image_writes cl_img_egl_image cl_khr_byte_addressable_store cl_khr_depth_images cl_khr_egl_event cl_khr_egl_image cl_khr_fp16 cl_khr_gl_sharing cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_image2d_from_buffer cl_khr_mipmap_image cl_khr_srgb_image_writes cl_khr_subgroups cl_qcom_create_buffer_from_image cl_qcom_ext_host_ptr cl_qcom_ion_host_ptr cl_qcom_perf_hint cl_qcom_other_image cl_qcom_subgroup_shuffle cl_qcom_vector_image_ops cl_qcom_extract_image_plane cl_qcom_android_native_buffer_host_ptr cl_qcom_protected_context cl_qcom_priority_hint cl_qcom_compressed_yuv_image_read cl_qcom_compressed_image cl_qcom_ext_host_ptr_iocoherent cl_qcom_accelerated_image_ops cl_qcom_ml_ops 
    *[COMPV INFO]: [UltBaseOpenCL] !!!Booom!!!, OpenCL successfully loaded [libOpenCL.so]
I/org.doubango.compv: *[COMPV INFO]: [UltOcrEngine] Tensorflow version: 1.12.3
    *[COMPV INFO]: [CompVBase] android/os/Build$VERSION.SDK_INT: 30
    *[COMPV INFO]: [CompVBase] android/os/Build.CPU_ABI: arm64-v8a
    *[COMPV INFO]: [CompVBase] android/os/Build.MODEL: GM1901
    *[COMPV INFO]: [CompVBase] android/os/Build.HARDWARE: qcom
W/imateCreditCar: Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (greylist, JNI, allowed)
W/imateCreditCar: Accessing hidden method Landroid/app/ActivityThread;->getApplication()Landroid/app/Application; (greylist, JNI, allowed)
I/org.doubango.compv: *[COMPV INFO]: [CompVBase] AID: ****
    *[COMPV INFO]: [UltCreditCardSdkEnginePrivate] **** Copyright (C) 2011-2021 Doubango Telecom <https://www.doubango.org> ****
    You're using an unlicensed version of ultimateCreditCard-SDK <https://github.com/DoubangoTelecom/ultimateCreditCard-SDK>
    without the rights to include the SDK in any form of commercial product.
    *[COMPV INFO]: [UltCreditCardSdkEnginePrivate] IC took 0 millis
    *[COMPV INFO]: [CompVCpu] Enabling asm code
    *[COMPV INFO]: [CompVCpu] Enabling intrinsic code
    *[COMPV INFO]: [UltCreditCardSdkEnginePrivate] recogn_tf_num_threads: 8
I/tflite: Initialized TensorFlow Lite runtime.
A/org.doubango.compv: ****[COMPV FATAL]: function: "newPtr()" 
    file: "..\source\ultimate_ocr_tensorflowlite_interpreter.cxx" 
    line: "514" 
    message: Assertion failed!
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5490 (imateCreditCard), pid 5490 (imateCreditCard)

**Comment by DoubangoTelecom** [comment]
I cannot reproduce the issue with 2.5.0. Try updating your code to that version. I have updated TensorflowLite to 2.5.0-rc1. I'll reopen the ticket if you still have the issue.
