### ISSUE TITLE
Detection Bounding Box

### ISSUE THREAD

**Issue by ftll574** [DoubangoTelecom/ultimateCreditCard-SDK#38]
Thanks for your repo first !
The online demo of credit card result seems very good. I'm interesting about your method. Is there any method to get the 
text bounding box of detection result ? Thanks.

**Comment by DoubangoTelecom** [comment]
> Thanks for your repo first ! The online demo of credit card result seems very good. I'm interesting about your method. Is there any method to get the text bounding box of detection result ? Thanks.

No
